name: Deploy Production Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy na AWS via Docker (Front)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_FRONTEND_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script_stop: true
          script: |
            cd /home/ec2-user/front-n1
            git fetch origin
            git checkout main
            git reset --hard origin/main

            # Limpeza preventiva para não lotar o disco da EC2
            docker image prune -f

            # Build e Restart automático
            docker compose up --build -d
            docker image prune -f