name: Deploy Staging Frontend

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Staging
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script_stop: true
          script: |
            # 1. Entra na pasta
            cd /home/ec2-user/front-n1
            
            # 2. Atualiza o código do Git
            git fetch origin
            git checkout develop
            git reset --hard origin/develop
            
            # 3. Roda APENAS o Docker (remova comandos de npm ou pm2 daqui)
            docker compose up --build -d
            
            # 4. Limpeza de segurança
            docker image prune -f